# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
import logging

from odoo import fields, models

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    _inherit = "sale.order"

    event_registration_id = fields.Many2one("event.registration", string="Stagiaire")

    def _prepare_invoice(self):
        """
        Copy event_registration_id to generated invoice.
        """
        res = super()._prepare_invoice()
        res["event_registration_id"] = self.event_registration_id.id
        return res

    def linked_to_registration(self):
        return (
            len(
                self.env["event.registration.financier"].search(
                    [("quotation_id", "=", self.id)]
                )
            )
            > 0
        )

    def action_confirm(self):
        res = super().action_confirm()

        # if sale order is linked to event.registration.financier, don't open wizard
        if (
            isinstance(res, dict)
            and res.get("xml_id") == "event_sale.action_sale_order_event_registration"
            and self.linked_to_registration()
        ):
            return True

        return res


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    def _update_registrations(
        self,
        confirm=True,
        cancel_to_draft=False,
        registration_data=None,
        mark_as_paid=False,
    ):
        # bypass _update_registrations if order generated by event registration
        if self.order_id.linked_to_registration():
            return
        return super()._update_registrations(
            confirm, cancel_to_draft, registration_data, mark_as_paid
        )
